### ISSUE TITLE
PHP inside comment loses syntax highlighting

### ISSUE THREAD

**Issue by itsamoreh** [chrisrhymes/gutenburg-comment-highlight#2]
First - thanks for making this extension! It's really nice to get some highlighting in the comments.

When using this extension, PHP inside the comments lose highlighting and is highlighted like a string.

With extension active:
<img width="1350" alt="screen-capture 2023-06-21 at 11 22 28 PM" src="https://github.com/chrisrhymes/gutenburg-comment-highlight/assets/12365909/8ca30fbd-814b-44a8-a13e-ab61b5ccf673">

Without extension active:
<img width="1379" alt="screen-capture 2023-06-21 at 11 23 21 PM" src="https://github.com/chrisrhymes/gutenburg-comment-highlight/assets/12365909/e3087ff5-ab79-4555-a576-f342c0b5551f">

**Comment by chrisrhymes** [comment]
Hello, please can you try the latest release (0.04). This should now support PHP syntax highlighting within the comment.

**Comment by itsamoreh** [comment]
Thanks! It's perfect!
